token_ttl: 5h

app:
  name: 'wcharge_mqtt'
  version: '1.0.0'

grpc:
  port: '9999'
  timeout: 120s

logger:
  log_level: 'debug'
  rollbar_env: 'wcharge_mqtt'

mqtt:
  url: 'mqtt://guest:guest@89.111.154.223:1883/'
  client_id: '10001'

